### ISSUE TITLE
HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings

### ISSUE THREAD

**Issue by salim-b** [Sam-Max/plugin.video.jacktorr#1]
Hi @Sam-Max 

I'm trying to use JackTorr (together with [Jacktook](https://github.com/Sam-Max/plugin.video.jacktook)) and running into the following error using the default configuration:

```
HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

<details><summary>Full log snippet:</summary>

```
2024-07-10 14:04:07.283 T:4345    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.ConnectionError'>
                                                   Error Contents: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 203, in _new_conn
                                                       sock = connection.create_connection(
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 85, in create_connection
                                                       raise err
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/connection.py", line 73, in create_connection
                                                       sock.connect(sa)
                                                   ConnectionRefusedError: [Errno 111] Connection refused
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 790, in urlopen
                                                       response = self._make_request(
                                                                  ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 496, in _make_request
                                                       conn.request(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 395, in request
                                                       self.endheaders()
                                                     File "/usr/lib/python3.11/http/client.py", line 1298, in endheaders
                                                     File "/usr/lib/python3.11/http/client.py", line 1058, in _send_output
                                                     File "/usr/lib/python3.11/http/client.py", line 996, in send
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 243, in connect
                                                       self.sock = self._new_conn()
                                                                   ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 218, in _new_conn
                                                       raise NewConnectionError(
                                                   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused
                                                   
                                                   The above exception was the direct cause of the following exception:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 486, in send
                                                       resp = conn.urlopen(
                                                              ^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 844, in urlopen
                                                       retries = retries.increment(
                                                                 ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 515, in increment
                                                       raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/service.py", line 9, in <module>
                                                       run()
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 144, in run
                                                       DaemonMonitor().start()
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 129, in start
                                                       self.onSettingsChanged()
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 125, in onSettingsChanged
                                                       self._update_daemon_settings()
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 101, in _update_daemon_settings
                                                       daemon_settings = self._get_daemon_settings()
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 79, in _get_daemon_settings
                                                       r = self._request(
                                                           ^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.jacktorr/lib/service.py", line 61, in _request
                                                       return request(
                                                              ^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 59, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 589, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 703, in send
                                                       r = adapter.send(request, **kwargs)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 519, in send
                                                       raise ConnectionError(e, request=request)
                                                   requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused'))
                                                   -->End of Python script error report<--

```

</details>

I'm completely new to JackTorr / TorrServer, so please excuse my possibly foolish question: Do I need to change the default configuration? If so, to what exactly?

I'm running Kodi 21.0 via CoreELEC 21.0 on a ODROID-N2-Plus.

**Comment by Sam-Max** [comment]
> Hi @Sam-Max
> 
> I'm trying to use JackTorr (together with [Jacktook](https://github.com/Sam-Max/plugin.video.jacktook)) and running into the following error using the default configuration:
> 
> ```
> HTTPConnectionPool(host='127.0.0.1', port=5665): Max retries exceeded with url: /settings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xcea0a008>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> Full log snippet:
> 
> I'm completely new to JackTorr / TorrServer, so please excuse my possibly foolish question: Do I need to change the default configuration? If so, to what exactly?
> 
> I'm running Kodi 21.0 via CoreELEC 21.0 on a ODROID-N2-Plus.

Sorry for the delay answer, Jacktorr has not inbuilt daemon to run the TorrServer service, you need to deploy TorrServer server on another pc using docker for example, and configure Jacktorr with that server information.

**Comment by salim-b** [comment]
Ok, I understand.

The README says

> JackTorr is an torrent streaming engine for Kodi that **implements** [TorrServer](https://github.com/YouROK/TorrServer), which provides several features like an http API for streaming, memory and disk cache, API auth, etc

so that might be interpreted a bit more ample than actually is the case by other folks, too, I guess 😅

Anyways, thanks for the great Jacktook add-on! I'm now using it together with torrest. Any particular advantage of TorrServer+JackTorr over torrest?

**Comment by Sam-Max** [comment]
> Ok, I understand.
> 
> The README says
> 
> > JackTorr is an torrent streaming engine for Kodi that **implements** [TorrServer](https://github.com/YouROK/TorrServer), which provides several features like an http API for streaming, memory and disk cache, API auth, etc
> 
> so that might be interpreted a bit more ample than actually is the case by other folks, too, I guess 😅
> 
> Anyways, thanks for the great Jacktook add-on! I'm now using it together with torrest. Any particular advantage of TorrServer+JackTorr over torrest?

Jacktorr+TorrServer has some advantages like you can configure basic auth in case you deploy on a remote server to protect remote access and you can also run torrents on RAM memory, not only on disk. Also TorrServer has a nice apk to control remote server.

**Comment by shak38** [comment]
Hi, nice addon! Is it possible or will be possible to use this on the same device with a local torrserver install (on android for example)? Thanks for Jacktook and jacktorr!
